=== api-evangelist/the-racing-api/json-schema/the-racing-api-app__models__na_results__-runner-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/the-racing-api/refs/heads/main/json-schema/the-racing-api-app__models__na_results__-runner-schema.json",
  "title": "app__models__na_results__Runner",
  "description": "app__models__na_results__Runner schema from The Racing API",
  "type": "object",
  "properties": {
    "breeder_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Breeder Name"
    },
    "horse_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Horse Name"
    },
    "jockey_first_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Jockey First Name"
    },
    "jockey_first_name_initial": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Jockey First Name Initial"
    },
    "jockey_last_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Jockey Last Name"
    },
    "owner_first_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Owner First Name"
    },
    "owner_last_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Owner Last Name"
    },
    "place_payoff": {
      "anyOf": [
        {
          "type": "number"
        },
        {
          "type": "null"
        }
      ],
      "title": "Place Payoff"
    },
    "program_number": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Program Number"
    },
    "program_number_stripped": {
      "anyOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "title": "Program Number Stripped"
    },
    "show_payoff": {
      "anyOf": [
        {
          "type": "number"
        },
        {
          "type": "null"
        }
      ],
      "title": "Show Payoff"
    },
    "sire_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Sire Name"
    },
    "trainer_first_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Trainer First Name"
    },
    "trainer_last_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Trainer Last Name"
    },
    "weight_carried": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Weight Carried"
    },
    "win_payoff": {
      "anyOf": [
        {
          "type": "number"
        },
        {
          "type": "null"
        }
      ],
      "title": "Win Payoff"
    }
  }
}

=== api-evangelist/the-racing-api/examples/the-racing-api-app__models__na_results__-runner-example.json
{
  "breeder_name": "Example Name",
  "horse_name": "Frankel",
  "jockey_first_name": "Example Name",
  "jockey_first_name_initial": "Example Name",
  "jockey_last_name": "Example Name",
  "owner_first_name": "Example Name",
  "owner_last_name": "Example Name",
  "place_payoff": "example-value",
  "program_number": "example-value",
  "program_number_stripped": "example-value",
  "show_payoff": "example-value",
  "sire_name": "Example Name",
  "trainer_first_name": "Example Name",
  "trainer_last_name": "Example Name",
  "weight_carried": "example-value",
  "win_payoff": "example-value"
}
