=== api-evangelist/the-racing-api/json-schema/the-racing-api-app__models__aus_races__-race-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/the-racing-api/refs/heads/main/json-schema/the-racing-api-app__models__aus_races__-race-schema.json",
  "title": "app__models__aus_races__Race",
  "description": "app__models__aus_races__Race schema from The Racing API",
  "type": "object",
  "properties": {
    "course": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Course"
    },
    "course_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Course Id"
    },
    "date": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Date"
    },
    "distance": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Distance"
    },
    "going": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Going"
    },
    "is_jump_out": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "type": "null"
        }
      ],
      "title": "Is Jump Out",
      "default": false
    },
    "is_trial": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "type": "null"
        }
      ],
      "title": "Is Trial",
      "default": false
    },
    "meet_id": {
      "type": "string",
      "title": "Meet Id"
    },
    "off_time": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Off Time"
    },
    "prizes": {
      "anyOf": [
        {
          "items": {},
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "title": "Prizes"
    },
    "prize_total": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Prize Total"
    },
    "class": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Class"
    },
    "race_conditions": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Race Conditions"
    },
    "race_group": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Race Group"
    },
    "race_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Race Name"
    },
    "race_number": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Race Number"
    },
    "race_status": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Race Status"
    },
    "state": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "State"
    },
    "runners": {
      "items": {
        "$ref": "#/components/schemas/app__models__aus_races__Runner"
      },
      "type": "array",
      "title": "Runners"
    },
    "winning_time": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Winning Time"
    },
    "winning_time_hundredths": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Winning Time Hundredths"
    }
  }
}

=== api-evangelist/the-racing-api/examples/the-racing-api-app__models__aus_races__-race-example.json
{
  "course": "Cheltenham",
  "course_id": "670189",
  "date": "2025-03-15",
  "distance": "example-value",
  "going": "good",
  "is_jump_out": false,
  "is_trial": false,
  "meet_id": "401225",
  "off_time": "example-value",
  "prizes": "example-value",
  "prize_total": "example-value",
  "class": "class_1",
  "race_conditions": "example-value",
  "race_group": "example-value",
  "race_name": "Example Name",
  "race_number": "example-value",
  "race_status": "active",
  "state": "example-value",
  "runners": [
    "example-value"
  ],
  "winning_time": "example-value",
  "winning_time_hundredths": "example-value"
}
