=== api-evangelist/the-racing-api/json-schema/the-racing-api-app__models__aus_races__-runner-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/the-racing-api/refs/heads/main/json-schema/the-racing-api-app__models__aus_races__-runner-schema.json",
  "title": "app__models__aus_races__Runner",
  "description": "app__models__aus_races__Runner schema from The Racing API",
  "type": "object",
  "properties": {
    "horse_id": {
      "type": "string",
      "title": "Horse Id"
    },
    "horse": {
      "type": "string",
      "title": "Horse"
    },
    "age": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Age"
    },
    "comment": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Comment"
    },
    "colour": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Colour"
    },
    "dam": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Dam"
    },
    "dam_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Dam Id"
    },
    "draw": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Draw"
    },
    "form": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Form"
    },
    "jockey": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Jockey"
    },
    "jockey_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Jockey Id"
    },
    "jockey_claim": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Jockey Claim"
    },
    "margin": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Margin"
    },
    "number": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Number"
    },
    "odds": {
      "anyOf": [
        {
          "items": {
            "$ref": "#/components/schemas/app__models__aus_races__RunnerOdds"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "title": "Odds"
    },
    "owner": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Owner"
    },
    "position": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Position"
    },
    "prize": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Prize"
    },
    "rating": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Rating"
    },
    "scratched": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "type": "null"
        }
      ],
      "title": "Scratched"
    },
    "sex": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Sex"
    },
    "silk_url": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Silk Url"
    },
    "sire": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Sire"
    },
    "sire_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Sire Id"
    },
    "sp": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Sp"
    },
    "stats": {
      "anyOf": [
        {
          "$ref": "#/components/schemas/RunnerStats"
        },
        {
          "type": "null"
        }
      ]
    },
    "trainer": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Trainer"
    },
    "trainer_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Trainer Id"
    },
    "weight": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Weight"
    }
  },
  "required": [
    "horse_id",
    "horse"
  ]
}

=== api-evangelist/the-racing-api/examples/the-racing-api-app__models__aus_races__-runner-example.json
{
  "horse_id": "622249",
  "horse": "example-value",
  "age": "example-value",
  "comment": "example-value",
  "colour": "example-value",
  "dam": "example-value",
  "dam_id": "285196",
  "draw": "example-value",
  "form": "example-value",
  "jockey": "example-value",
  "jockey_id": "491719",
  "jockey_claim": "example-value",
  "margin": "example-value",
  "number": "example-value",
  "odds": "example-value",
  "owner": "example-value",
  "position": "example-value",
  "prize": "example-value",
  "rating": "example-value",
  "scratched": "example-value",
  "sex": "example-value",
  "silk_url": "example-value",
  "sire": "example-value",
  "sire_id": "324932",
  "sp": "example-value",
  "stats": "example-value",
  "trainer": "example-value",
  "trainer_id": "957516",
  "weight": "example-value"
}
