=== api-evangelist/the-racing-api/json-schema/the-racing-api-app__models__na_results__-race-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/the-racing-api/refs/heads/main/json-schema/the-racing-api-app__models__na_results__-race-schema.json",
  "title": "app__models__na_results__Race",
  "description": "app__models__na_results__Race schema from The Racing API",
  "type": "object",
  "properties": {
    "age_restriction": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Age Restriction"
    },
    "age_restriction_description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Age Restriction Description"
    },
    "also_ran": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "items": {},
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "title": "Also Ran"
    },
    "breed": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Breed"
    },
    "distance_description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Distance Description"
    },
    "distance_unit": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Distance Unit"
    },
    "distance_value": {
      "anyOf": [
        {
          "type": "integer"
        },
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Distance Value"
    },
    "fraction": {
      "anyOf": [
        {
          "$ref": "#/components/schemas/Fraction"
        },
        {
          "type": "null"
        }
      ]
    },
    "grade": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Grade"
    },
    "maximum_claim_price": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Maximum Claim Price"
    },
    "minimum_claim_price": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Minimum Claim Price"
    },
    "off_time": {
      "anyOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "title": "Off Time"
    },
    "payoffs": {
      "anyOf": [
        {
          "items": {
            "$ref": "#/components/schemas/Payoff"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "title": "Payoffs"
    },
    "post_time": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Post Time"
    },
    "post_time_long": {
      "anyOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "title": "Post Time Long"
    },
    "race_class": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Race Class"
    },
    "race_key": {
      "anyOf": [
        {
          "$ref": "#/components/schemas/RaceKey"
        },
        {
          "type": "null"
        }
      ]
    },
    "race_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Race Name"
    },
    "race_restriction": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Race Restriction"
    },
    "race_restriction_description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Race Restriction Description"
    },
    "race_type": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Race Type"
    },
    "race_type_description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Race Type Description"
    },
    "runners": {
      "anyOf": [
        {
          "items": {
            "$ref": "#/components/schemas/app__models__na_results__Runner"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "title": "Runners"
    },
    "scratches": {
      "anyOf": [
        {
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "title": "Scratches"
    },
    "sex_restriction": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Sex Restriction"
    },
    "sex_restriction_description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Sex Restriction Description"
    },
    "surface": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Surface"
    },
    "surface_description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Surface Description"
    },
    "time_zone": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Time Zone"
    },
    "total_purse": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Total Purse"
    },
    "track_condition_description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Track Condition Description"
    },
    "track_name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Track Name"
    },
    "wager_types": {
      "anyOf": [
        {
          "items": {
            "$ref": "#/components/schemas/WagerType"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "title": "Wager Types"
    }
  }
}

=== api-evangelist/the-racing-api/examples/the-racing-api-app__models__na_results__-race-example.json
{
  "age_restriction": "example-value",
  "age_restriction_description": "example-value",
  "also_ran": "example-value",
  "breed": "example-value",
  "distance_description": "example-value",
  "distance_unit": "example-value",
  "distance_value": "example-value",
  "fraction": "example-value",
  "grade": "example-value",
  "maximum_claim_price": "example-value",
  "minimum_claim_price": "example-value",
  "off_time": "example-value",
  "payoffs": "example-value",
  "post_time": "example-value",
  "post_time_long": "example-value",
  "race_class": "class_1",
  "race_key": "example-value",
  "race_name": "Example Name",
  "race_restriction": "example-value",
  "race_restriction_description": "example-value",
  "race_type": "flat",
  "race_type_description": "flat",
  "runners": "example-value",
  "scratches": "example-value",
  "sex_restriction": "example-value",
  "sex_restriction_description": "example-value",
  "surface": "example-value",
  "surface_description": "example-value",
  "time_zone": "example-value",
  "total_purse": "example-value",
  "track_condition_description": "example-value",
  "track_name": "Example Name",
  "wager_types": "flat"
}
